import type { ExamPreset } from "@/types/exam";

export const EXAM_PRESETS: ExamPreset[] = [
  {
    id: "ssc-cgl",
    name: "SSC CGL",
    fullName: "Staff Selection Commission – Combined Graduate Level",
    category: "central",
    photo: { widthPx: 200, heightPx: 230, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 140, heightPx: 60, minKB: 10, maxKB: 20, format: "jpeg", background: "#FFFFFF" },
    notes: "White background mandatory for photo. Signature on plain white paper.",
  },
  {
    id: "ssc-chsl",
    name: "SSC CHSL",
    fullName: "Staff Selection Commission – Combined Higher Secondary Level",
    category: "central",
    photo: { widthPx: 200, heightPx: 230, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 140, heightPx: 60, minKB: 10, maxKB: 20, format: "jpeg", background: "#FFFFFF" },
    notes: "Same specs as SSC CGL. White background, recent passport-size photo.",
  },
  {
    id: "ssc-gd",
    name: "SSC GD",
    fullName: "Staff Selection Commission – General Duty Constable",
    category: "central",
    photo: { widthPx: 200, heightPx: 230, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 100, heightPx: 60, minKB: 10, maxKB: 20, format: "jpeg", background: "#FFFFFF" },
    notes: "White background. Recent colour passport photo required.",
  },
  {
    id: "upsc-cse",
    name: "UPSC CSE",
    fullName: "Union Public Service Commission – Civil Services Exam (IAS/IPS)",
    category: "central",
    photo: { widthPx: 300, heightPx: 400, minKB: 3, maxKB: 300, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 300, heightPx: 100, minKB: 1, maxKB: 300, format: "jpeg", background: "#FFFFFF" },
    notes: "Light background preferred. Photo must show face clearly.",
  },
  {
    id: "rrb-ntpc",
    name: "RRB NTPC",
    fullName: "Railway Recruitment Board – Non-Technical Popular Category",
    category: "railway",
    photo: { widthPx: 150, heightPx: 200, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 150, heightPx: 100, minKB: 10, maxKB: 40, format: "jpeg", background: "#FFFFFF" },
    notes: "White background. Recent passport-size photograph required.",
  },
  {
    id: "rrb-group-d",
    name: "RRB Group D",
    fullName: "Railway Recruitment Board – Group D",
    category: "railway",
    photo: { widthPx: 150, heightPx: 200, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 150, heightPx: 100, minKB: 10, maxKB: 40, format: "jpeg", background: "#FFFFFF" },
    notes: "Same specs as RRB NTPC. White/light background.",
  },
  {
    id: "ibps-po",
    name: "IBPS PO",
    fullName: "Institute of Banking Personnel Selection – Probationary Officer",
    category: "banking",
    photo: { widthPx: 200, heightPx: 230, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 140, heightPx: 60, minKB: 10, maxKB: 20, format: "jpeg", background: "#FFFFFF" },
    notes: "White background mandatory. Signature in black/blue ink on white paper.",
  },
  {
    id: "ibps-clerk",
    name: "IBPS Clerk",
    fullName: "Institute of Banking Personnel Selection – Clerical Cadre",
    category: "banking",
    photo: { widthPx: 200, heightPx: 230, minKB: 20, maxKB: 50, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 140, heightPx: 60, minKB: 10, maxKB: 20, format: "jpeg", background: "#FFFFFF" },
    notes: "Same specs as IBPS PO. White background.",
  },
  {
    id: "sbi-po",
    name: "SBI PO",
    fullName: "State Bank of India – Probationary Officer",
    category: "banking",
    photo: { widthPx: 240, heightPx: 320, minKB: 20, maxKB: 100, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 160, heightPx: 96, minKB: 10, maxKB: 40, format: "jpeg", background: "#FFFFFF" },
    notes: "White background. Photo and signature in JPEG only.",
  },
  {
    id: "sbi-clerk",
    name: "SBI Clerk",
    fullName: "State Bank of India – Junior Associates (Clerical Cadre)",
    category: "banking",
    photo: { widthPx: 240, heightPx: 320, minKB: 20, maxKB: 100, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 160, heightPx: 96, minKB: 10, maxKB: 40, format: "jpeg", background: "#FFFFFF" },
    notes: "Same specs as SBI PO.",
  },
  {
    id: "neet",
    name: "NEET UG",
    fullName: "National Eligibility cum Entrance Test – Undergraduate",
    category: "medical",
    photo: { widthPx: 276, heightPx: 354, minKB: 10, maxKB: 200, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 276, heightPx: 118, minKB: 10, maxKB: 100, format: "jpeg", background: "#FFFFFF" },
    notes: "White background. Colour passport photo, face visible clearly.",
  },
  {
    id: "jee-main",
    name: "JEE Main",
    fullName: "Joint Entrance Examination – Main",
    category: "engineering",
    photo: { widthPx: 200, heightPx: 230, minKB: 4, maxKB: 100, format: "jpeg", background: "#FFFFFF" },
    signature: { widthPx: 200, heightPx: 80, minKB: 4, maxKB: 30, format: "jpeg", background: "#FFFFFF" },
    notes: "White or light background. Clear frontal photo required.",
  },
];

export const EXAM_PRESETS_BY_ID: Record<string, ExamPreset> = Object.fromEntries(
  EXAM_PRESETS.map((p) => [p.id, p])
);

export const EXAM_CATEGORIES = {
  central: "Central Government",
  railway: "Railways",
  banking: "Banking",
  medical: "Medical",
  engineering: "Engineering",
  state: "State Government",
} as const;
